// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlumsailTest.DAL.Sql;

namespace PlumsailTest.DAL.Sql.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PlumsailTest.Domain.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FormItemSelectValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormItemTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("FormItemSelectValueId");

                    b.HasIndex("FormItemTemplateId");

                    b.ToTable("FormItems");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItemSelectValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormItemTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormItemTemplateId");

                    b.ToTable("FormItemSelectValues");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormItemTemplates");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.Form", b =>
                {
                    b.HasOne("PlumsailTest.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany()
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItem", b =>
                {
                    b.HasOne("PlumsailTest.Domain.Entities.Form", "Form")
                        .WithMany("FormItems")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumsailTest.Domain.Entities.FormItemSelectValue", "FormItemSelectValue")
                        .WithMany()
                        .HasForeignKey("FormItemSelectValueId");

                    b.HasOne("PlumsailTest.Domain.Entities.FormItemTemplate", "FormItemTemplate")
                        .WithMany()
                        .HasForeignKey("FormItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("FormItemSelectValue");

                    b.Navigation("FormItemTemplate");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItemSelectValue", b =>
                {
                    b.HasOne("PlumsailTest.Domain.Entities.FormItemTemplate", "FormItemTemplate")
                        .WithMany("Values")
                        .HasForeignKey("FormItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormItemTemplate");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItemTemplate", b =>
                {
                    b.HasOne("PlumsailTest.Domain.Entities.FormTemplate", "FormTemplate")
                        .WithMany("ItemTemplates")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.Form", b =>
                {
                    b.Navigation("FormItems");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormItemTemplate", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("PlumsailTest.Domain.Entities.FormTemplate", b =>
                {
                    b.Navigation("ItemTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
